env = {AX_IP = "10.0.2.15", AX_GW = "10.0.2.2"}
features = [
  "ax-feat/rtc",
  "ax-driver/serial",
  "ax-driver/virtio-blk",
  "ax-driver/virtio-net",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "ax-driver/virtio-socket",
  "ax-driver/xhci-pci",
  "starry-kernel/input",
]
log = "Warn"
target = "riscv64gc-unknown-none-elf"
