features = [
  "ax-runtime/display",
  "ax-runtime/rtc",
  "ax-driver/serial",
  "ax-driver/nvme",
  "ax-driver/virtio-net",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "ax-driver/virtio-socket",
  "ax-driver/xhci-pci",
  "starry-kernel/input",
  "starry-kernel/vsock",
]
log = "Warn"
target = "aarch64-unknown-none-softfloat"
