target = "aarch64-unknown-none-softfloat"
features = [
  "ax-driver/rockchip-soc",
  "ax-driver/rockchip-sdhci",
  "ax-driver/rockchip-dwmmc",
  "ax-driver/phytium-mci",
]
log = "Info"
max_cpu_num = 1
