args = [
    "-machine", "virt",
    "-cpu", "la464",
    "-nographic",
    "-m", "128M",
    "-device", "virtio-blk-pci,drive=disk0",
    "-drive", "id=disk0,if=none,format=raw,file=${workspace}/target/loongarch64-unknown-none-softfloat/rootfs-loongarch64.img",
    "-device", "virtio-net-pci,netdev=net0",
    "-netdev", "user,id=net0",
]
uefi = false
to_bin = true
shell_prefix = "root@starry:"
shell_init_cmd = "/usr/bin/test-rlimit-stack"
success_regex = ["(?m)DONE: \\d+ pass, 0 fail"]
fail_regex = ['(?i)\bpanic(?:ked)?\b', '(?m)FAIL']
timeout = 30
