args = [
  "-nographic",
  "-machine",
  "virt",
  "-bios",
  "default",
  "-smp",
  "4",
  "-d",
  "int,guest_errors",
  "-D",
  "qemu.log",
]
fail_regex = [
  "Panicked:",
]
success_regex = [
  "All tests passed!"
]
to_bin = true
uefi = false
