args = [
    "-machine",
    "virt",
    "-cpu",
    "la464",
    "-m",
    "128M",
    "-smp",
    "4",
    "-nographic",
    "-device",
    "virtio-net-pci,netdev=net0",
    "-netdev",
    "user,id=net0",
    "-serial",
    "mon:stdio",
]
uefi = false
to_bin = true
success_regex = ["HTTP client tests run OK!"]
fail_regex = ["(?i)\\bpanic(?:ked)?\\b"]
