args = [
    "-machine",
    "q35",
    "-cpu",
    "max",
    "-m",
    "128M",
    "-smp",
    "1",
    "-nographic",
    "-serial",
    "mon:stdio",
]
uefi = false
to_bin = false
success_regex = [
    "(?s)emitting raw backtrace report \\(normal fp chain\\)\\.\\.\\..*BACKTRACE_BEGIN\\b.*\\bkind=raw\\b.*BT\\s+0\\s+ip=0x[0-9a-fA-F]+\\s+fp=0x[0-9a-fA-F]+.*BT\\s+1\\s+ip=0x[0-9a-fA-F]+\\s+fp=0x[0-9a-fA-F]+.*BACKTRACE_END\\b.*test pass",
]
fail_regex = ["(?i)\\bpanic(?:ked)?\\b"]
