get_filename_component(STARRY_ARCH_FILTER_DIR "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)

function(starry_arch_filtered_executable target arch_regex skip_message)
    if(CMAKE_C_COMPILER_TARGET MATCHES "${arch_regex}")
        add_executable(${target} ${ARGN})
    else()
        add_executable(${target} "${STARRY_ARCH_FILTER_DIR}/arch_skip.c")
        target_compile_definitions(${target} PRIVATE "STARRY_SKIP_MESSAGE=\"${skip_message}\"")
    endif()
endfunction()
