args = [
    "-nographic",
    "-m",
    "1G",
    "-device",
    "virtio-blk-pci,drive=disk0",
    "-drive",
    "id=disk0,if=none,format=raw,file=${workspace}/tmp/axbuild/rootfs/rootfs-x86_64-alpine.img",
    "-device",
    "virtio-net-pci,netdev=net0",
    "-netdev",
    "user,id=net0",
]
uefi = false
to_bin = false
shell_prefix = "root@starry:"
shell_init_cmd = "/usr/bin/nginx-runner.sh debug sendfile-on-debug"
success_regex = ["(?m)^NGINX_RUNNER_PASSED\\b"]
fail_regex = ["(?i)\\bpanic(?:ked)?\\b", "(?m)^NGINX_RUNNER_FAILED\\b"]
timeout = 3600
