target = "riscv64gc-unknown-none-elf"
env = {AX_IP = "10.0.2.15", AX_GW = "10.0.2.2"}
log = "Warn"
features = [
  "ax-hal/riscv64-qemu-virt",
  "qemu",
  "ax-driver/pci",
  "ax-driver/virtio-blk",
  "ax-driver/virtio-net",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "ax-driver/virtio-socket",
  "kcov",
]
plat_dyn = false
