args = [
    "-machine",
    "virt",
    "-cpu",
    "rv64",
    "-m",
    "512M",
    "-smp",
    "4",
    "-nographic",
    "-serial",
    "mon:stdio",
]
uefi = false
to_bin = true
success_regex = ["Hello, C app!"]
fail_regex = ['(?i)\bpanic(?:ked)?\b']
timeout = 120
