name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - "*"

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: check
