args = [
  "-nographic",
  "-d",
  "int,mmu,guest_errors",
  "-D",
  "qemu.log",
]
fail_regex = [
  "Panicked:",
  "!!!! Can't find image information. !!!!",
]
success_regex = [
  "All tests passed!",
]
to_bin = true
uefi = true
