args = [
  "-nographic",
  "-cpu",
  "cortex-a72",
  "-machine",
  "virt,virtualization=on,gic-version=3",
  "-smp",
  "4",
  "-device",
  "virtio-blk-device,drive=disk0",
  "-drive",
  "id=disk0,if=none,format=raw,file=${workspace}/target/rootfs/rootfs-aarch64-alpine.img",
  "-append",
  "root=/dev/vda rw init=/bin/sh",
  "-m",
  "8g",
]
build_config = "os/axvisor/configs/board/qemu-aarch64.toml"
vmconfigs = ["os/axvisor/configs/vms/linux-aarch64-qemu-smp1.toml"]
fail_regex = [
  "(?i)\\bpanic(?:ked)?\\b",
  "(?i)kernel panic",
  "(?i)login incorrect",
  "(?i)permission denied",
]
success_regex = ["(?m)^guest test pass!\\s*$"]
shell_prefix = "~ #"
shell_init_cmd = "pwd && echo 'guest test pass!'"
to_bin = true
uefi = false
