# Build-time config template for StarryOS on SG2002.
target = "riscv64gc-unknown-none-elf"
env = {}
features = [
  "starry-kernel/sg2002",
  "axplat-dyn/thead-mae",
  "ax-driver/sg2002-placeholder",
  "ax-driver/cvsd",
  "ax-driver/serial",
]
log = "Info"
max_cpu_num = 1
plat_dyn = true
