target = "x86_64-unknown-none"
env = {}
log = "Warn"
features = [
  "ax-feat/rtc",
  "ax-feat/display",
  "ax-driver/serial",
  "ax-driver/virtio-blk",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "starry-kernel/input",
]
