board_type = "OrangePi-5-Plus"
shell_prefix = "root@starry:/root #"
shell_init_cmd = "echo 'STARRY_ORANGEPI_BOOT_OK'"
success_regex = ["(?m)^STARRY_ORANGEPI_BOOT_OK\\s*$"]
fail_regex = ['(?i)\bpanic(?:ked)?\b']
timeout = 300
