target = "loongarch64-unknown-none-softfloat"
log = "Warn"
features = [
  "ax-hal/loongarch64-qemu-virt",
  "qemu",
  "ax-driver/plat-static",
  "ax-driver/virtio-blk",
  "ax-driver/virtio-net",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "ax-driver/virtio-socket",
]
plat_dyn = false
