env = { UIMAGE = "y" }
features = [
  "starry-kernel/sg2002-wifi",
  "axplat-dyn/thead-mae",
  "ax-driver/sg2002-placeholder",
  "ax-driver/cvsd",
  "ax-driver/serial",
]
log = "Info"
plat_dyn = true
target = "riscv64gc-unknown-none-elf"
