env = {}
features = [
  "ax-driver/virtio-blk",
  "ax-driver/virtio-net",
  "starry-kernel/input",
  "starry-kernel/vsock",
  "ax-driver/intel-net",
]
log = "Warn"
plat_dyn = true
target = "aarch64-unknown-none-softfloat"
