env = {}
features = [
  "starry-kernel/input",
  "starry-kernel/vsock", # auxilary features
  "axplat-dyn/intel-net",
  "axplat-dyn/virtio-net-pci",
]
log = "Warn"
plat_dyn = true
target = "aarch64-unknown-none-softfloat"
