features = [
  "ax-runtime/display",
  "ax-runtime/rtc",
  "ax-driver/serial",
  "ax-driver/virtio-blk",
  "ax-driver/virtio-net",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "ax-driver/virtio-socket",
  "starry-kernel/input",
  "starry-kernel/vsock",
]
log = "Warn"
target = "riscv64gc-unknown-none-elf"
