target = "x86_64-unknown-none"
log = "Warn"
features = [
  "axplat-dyn/efi",
  "ax-driver/virtio-blk",
  "ax-driver/virtio-net",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "ax-driver/virtio-socket",
]
