args = [
    "-nographic", "-cpu", "rv64",
    "-m", "512M",
    "-smp", "4",
    "-device", "virtio-blk-pci,drive=disk0",
    "-drive", "id=disk0,if=none,format=raw,file=${workspace}/tmp/axbuild/rootfs/rootfs-riscv64-alpine.img",
    "-device", "virtio-net-pci,netdev=net0",
    "-netdev", "user,id=net0",
]
uefi = false
to_bin = true
shell_prefix = "root@starry:"
shell_init_cmd = "/usr/bin/test-futex-wake-op-smp"
success_regex = ['PASS: FUTEX_WAKE_OP SMP atomic ADD \d+/\d+']
fail_regex = ['(?i)\bpanic(?:ked)?\b', '(?m)FAIL']
timeout = 360
