env = { AX_IP = "10.0.2.15", AX_GW = "10.0.2.2" }
features = [
    "ax-std/bus-mmio",
    "fs",
    "sdmmc",
    "phytium-blk",
]
log = "Info"
plat_dyn = true
target = "aarch64-unknown-none-softfloat"
vm_configs = []
