env = { AX_IP = "10.0.2.15", AX_GW = "10.0.2.2" }
features = [
    "ax-std/bus-mmio",
    "ept-level-4",
    "fs",
    "sstc"
]
log = "Info"
target = "riscv64gc-unknown-none-elf"
vm_configs = []
max_cpu_num = 4
