cargo_args = [
#     "--config",
#     'target.aarch64-unknown-none-softfloat.rustflags = ["-Crelocation-model=pic", "-Clink-args=-pie", "-Clink-args=-znostart-stop-gc", "-Clink-args=-Taxplat.x"]',
]
features = [
    "ept-level-4",
    "axstd/bus-mmio",
    "dyn-plat",
]
log = "Info"
target = "aarch64-unknown-none-softfloat"
to_bin = true
vm_configs = []
