args = [
    "-nographic",
    "-machine",
    "virt",
    "-cpu",
    "cortex-a53",
    "-device",
    "virtio-blk-pci,drive=disk0",
    "-drive",
    "id=disk0,if=none,format=raw,file=${workspace}/tmp/axbuild/rootfs/rootfs-aarch64-alpine.img",
    "-device",
    "virtio-net-pci,netdev=net0",
    "-netdev",
    "user,id=net0",
    "-device",
    "qemu-xhci,id=xhci,msi=off,msix=off",
    "-drive",
    "id=usbdisk,if=none,format=raw,snapshot=on,file=${workspace}/tmp/axbuild/rootfs/rootfs-aarch64-busybox.img",
    "-device",
    "usb-storage,bus=xhci.0,drive=usbdisk,serial=starry-usb-storage",
]
uefi = false
to_bin = true
shell_prefix = "root@starry:"
shell_init_cmd = "/usr/bin/usb-storage-test"
success_regex = ["(?m)^USB storage tests passed!\\s*$"]
fail_regex = ['(?i)\bpanic(?:ked)?\b', "USB storage test failed"]
timeout = 60
