[unstable]
build-std = ["core", "alloc"]

[target.'cfg(target_os = "none")']
runner = "cargo osrun"

[target.loongarch64-unknown-none-softfloat]
rustflags = [
  "-C",
  "relocation-model=pic",
  "-Clink-args=-pie",
  "-Clink-args=-znostart-stop-gc",
  "-Clink-args=-Tlink.x",
]
