[target.'cfg(not(any(windows, unix)))']
runner = "cargo osrun"

[target.loongarch64-unknown-none-softfloat]
rustflags = [
  "-C",
  "relocation-model=pic",
  "-Clink-args=-pie",
  "-Clink-args=-znostart-stop-gc",
  "-Clink-args=-Tlink.x",
]

[target.aarch64-unknown-none-softfloat]
rustflags = [
  "-C",
  "relocation-model=pic",
  "-Clink-args=-pie",
  "-Clink-args=-znostart-stop-gc",
  "-Clink-args=-Tlink.x",
]
