features = [
  "ax-feat/display",
  "ax-feat/rtc",
  "ax-driver/serial",
  "ax-driver/nvme",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "ax-driver/virtio-socket",
  "starry-kernel/input",
  "starry-kernel/vsock",
]
log = "Warn"
target = "riscv64gc-unknown-none-elf"
