target = "loongarch64-unknown-none-softfloat"
env = {}
log = "Warn"
features = [
  "ax-hal/loongarch64-qemu-virt",
  "qemu",
  "ax-driver/plat-static",
  "ax-driver/nvme",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "ax-driver/virtio-socket",
]
plat_dyn = false
