# Push Workflow
# References shared workflow from axci

name: Sync To Parent Repository

on:
  push:
    branches:
      - main
      - zcs
  workflow_dispatch:

jobs:
  sync-to-parent:
    uses: arceos-hypervisor/axci/.github/workflows/push.yml@main
    secrets: inherit
