target = "riscv64gc-unknown-none-elf"
log = "Warn"
features = [
  "ax-feat/display",
  "ax-feat/rtc",
  "ax-driver/serial",
  "ax-driver/virtio-blk",
  "ax-driver/virtio-net",
  "starry-kernel/input",
  "starry-kernel/vsock",
]
