target = "riscv64gc-unknown-none-elf"
log = "Warn"
features = [
  "ax-runtime/display",
  "ax-runtime/rtc",
  "ax-driver/serial",
  "ax-driver/virtio-blk",
  "ax-driver/virtio-net",
  "starry-kernel/input",
  "starry-kernel/vsock",
]
