args = [
    "-nographic",
    "-machine",
    "virt",
    "-cpu",
    "cortex-a53",
    "-device",
    "virtio-blk-pci,drive=disk0",
    "-drive",
    "id=disk0,if=none,format=raw,file=${workspace}/tmp/axbuild/rootfs/rootfs-aarch64-alpine.img",
    "-device",
    "virtio-net-pci,netdev=net0",
    "-netdev",
    "user,id=net0",
    "-audiodev",
    "none,id=audio0",
    "-device",
    "qemu-xhci,id=xhci,msi=off,msix=off",
    "-device",
    "usb-audio,bus=xhci.0,audiodev=audio0,multi=off",
]
uefi = false
to_bin = true
shell_prefix = "root@starry:"
shell_init_cmd = "/usr/bin/usb-audio-iso-test"
success_regex = ["(?m)^USB audio iso tests passed!\\s*$"]
fail_regex = ['(?i)\bpanic(?:ked)?\b', "USB audio iso test failed"]
timeout = 60
