args = [
  "-nographic",
  "-machine",
  "q35",
  "-smp",
  "1",
  "-d",
  "int,mmu,guest_errors",
  "-D",
  "qemu.log",
]
fail_regex = [
  "FAILED",
  "Panicked:",
  "!!!! Can't find image information. !!!!",
]
success_regex = [
  "All tests passed!",
]
to_bin = true
uefi = true
