name: Check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustc --version
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
