env = {AX_IP = "10.0.2.15", AX_GW = "10.0.2.2"}
features = [
  "ax-hal/plat-dyn",
  "ax-feat/display",
  "ax-feat/rtc",
  "ax-driver/pci",
  "ax-driver/rtc",
  "ax-driver/virtio-blk",
  "ax-driver/virtio-net",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "ax-driver/virtio-socket",
  "starry-kernel/input",
  "starry-kernel/plat-dyn",
  "starry-kernel/vsock",
  "starryos/buddy-slab",
]
max_cpu_num = 4
log = "Warn"
plat_dyn = true
target = "aarch64-unknown-none-softfloat"
