args = [
    "-machine",
    "q35",
    "-nographic",
    "-m",
    "512M",
    "-device",
    "virtio-blk-pci,drive=disk0",
    "-drive",
    "id=disk0,if=none,format=raw,file=${workspace}/tmp/axbuild/rootfs/rootfs-x86_64-alpine.img",
    "-device",
    "virtio-net-pci,netdev=net0",
    "-netdev",
    "user,id=net0",
]
uefi = false
to_bin = false
shell_prefix = "root@starry:"
shell_init_cmd = "/usr/bin/test_nix.sh"
success_regex = [
    "(?m)^NIX_NOSANDBOX_COMPLETE\\s*$",
]
fail_regex = [
    '(?i)\bpanic(?:ked)?\b',
    '(?i)\bfatal\b',
    "(?m)^NIX_NOSANDBOX_TEST_FAILED\\s*$",
]
timeout = 1200
