features = [
  "ax-hal/riscv64-qemu-virt",
  "qemu",
  "ax-driver/virtio-blk",
  "ax-driver/virtio-net",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "ax-driver/virtio-socket",
]
log = "Warn"
axconfig_overrides = ["plat.phys-memory-size=0x3_0000_0000"]
plat_dyn = false
target = "riscv64gc-unknown-none-elf"
