args = [
    "-machine",
    "virt",
    "-cpu",
    "rv64",
    "-m",
    "512M",
    "-smp",
    "4",
    "-nographic",
    "-serial",
    "mon:stdio",
]
uefi = false
to_bin = true
success_regex = ["(?ms)BACKTRACE_BEGIN.*^BT 0 ip=0x[1-9a-fA-F][0-9a-fA-F]* fp=0x[0-9a-fA-F]+\\s*$.*^BT 1 ip=0x[1-9a-fA-F][0-9a-fA-F]* fp=0x[0-9a-fA-F]+\\s*$.*^test pass\\s*$"]
fail_regex = ["(?i)\\bpanic(?:ked)?\\b"]
