env = { AX_IP = "10.0.2.15", AX_GW = "10.0.2.2" }
features = [
    "fs",
    "phytium-mci",
]
log = "Info"
plat_dyn = true
target = "aarch64-unknown-none-softfloat"
vm_configs = ["os/axvisor/configs/vms/phytiumpi/linux-smp1.toml"]
