env = {AX_IP = "10.0.2.15", AX_GW = "10.0.2.2"}
features = [
  "ax-feat/display",
  "ax-feat/rtc",
  "ax-driver/virtio-blk",
  "ax-driver/virtio-net",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "ax-driver/virtio-socket",
  "starry-kernel/input",
  "starry-kernel/vsock",
]
max_cpu_num = 4
log = "Warn"
target = "aarch64-unknown-none-softfloat"
