# Build-time config for the Orange Pi 5 Plus UVC Starry example.
target = "aarch64-unknown-none-softfloat"
env = {}
features = [
  "ax-feat/bus-mmio",
  "ax-feat/driver-sdmmc",
  "starry-kernel/plat-dyn",
  "axplat-dyn/rockchip-soc",
  "axplat-dyn/rockchip-dwc-xhci",
  "axplat-dyn/sdmmc",
  "axplat-dyn/simple-sdmmc",
]
log = "Info"
max_cpu_num = 1
plat_dyn = true
