args = [
    "-nographic",
    "-m", "2048M",
    "-cpu", "max",
    "-device", "virtio-blk-pci,drive=disk0",
    "-drive", "id=disk0,if=none,format=raw,file=${workspace}/tmp/axbuild/rootfs/rootfs-x86_64-higress.img",
    "-device", "virtio-net-pci,netdev=net0",
    "-netdev", "user,id=net0",
]
uefi = false
to_bin = false
shell_prefix = "root@starry:"
shell_init_cmd = "/usr/bin/run-higress.sh"
success_regex = ["(?m)^TEST PASSED$"]
fail_regex = [
    "(?m)^TEST FAILED$",
    "(?i)\\bpanic(?:ked)?\\b",
    "(?i)kernel panic",
    "(?i)unimplemented syscall",
    "(?i)enosys",
    "(?i)enoprotoopt",
]
timeout = 3600
