[package]
name = "ax-plat-example" # to be overwritten
version = "0.2.0"       # to be overwritten
edition = "2021"        # to be overwritten

[features]
irq = ["ax-plat/irq"]
smp = ["ax-plat/smp"]

[dependencies]
axconfig-macros = "0.2"
ax-plat = "0.3"
