[system.Cargo]
args = [
  "-Z", "build-std=core,alloc"  
]
features = []
package = "test-suit-async"
post_build_cmds = []
pre_build_cmds = []
target = "loongarch64-unknown-none-softfloat"
to_bin = true

[system.Cargo.env]