name: Release-plz

on:
  push:
    branches:
      - dev

jobs:
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/${{ github.repository }}-container:latest
    #   credentials:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    if: ${{ github.repository_owner == 'rcore-os' }}
    permissions:
      contents: write
      packages: read
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: true
      - &install-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  # release-plz-pr:
  #   name: Release-plz PR
  #   runs-on: ubuntu-latest
  #   if: ${{ github.repository_owner == 'rcore-os' }}
  #   permissions:
  #     pull-requests: write
  #     contents: write
  #   concurrency:
  #     group: release-plz-${{ github.ref }}
  #     cancel-in-progress: false
  #   steps:
  #     - *checkout
  #     - *install-rust
  #     - name: Run release-plz
  #       uses: release-plz/action@v0.5
  #       with:
  #         command: release-pr
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
