name: Check, Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        arch: [loongarch64, aarch64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - &setup-libudenv
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libudev-dev
          version: 1.0
      - name: Install toolchain
        run: rustup show
      - name: Check rust version
        run: rustc --version --verbose

      - name: Setup QEMU
        uses: arceos-org/setup-qemu@v1
        with:
          version: 10.1.0
          arch_list: ${{ matrix.arch }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: test
          cache-targets: false

      # - name: Install cargo-binutils
      #   run: cargo install cargo-binutils
      # - name: Install ostool
      #   run: cargo install ostool

      - uses: cargo-bins/cargo-binstall@main

      - name: Install ostool
        run: cargo binstall ostool

      - name: Install cargo-binutils
        run: |
          cargo-binstall \
            --pkg-url="{ repo }/releases/download/v{ version }/{ target }.tar.gz" \
            --pkg-fmt="tgz" \
            cargo-binutils

      - name: Add Target
        run: rustc --version
      - name: Check code format
        run: cargo fmt --all -- --check

      - uses: taiki-e/install-action@cargo-hack

      - name: Clippy for workspace
        run: cargo clippy --target ${{ matrix.arch }}-unknown-none-softfloat -- -D warnings

      - name: Build test
        run: ./test_${{ matrix.arch }}.sh
