name: Build & Test

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test_std:
    name: Test with std
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-container:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: test
          cache-targets: false

      - run: rustc --version
      - run: cargo xtask test std

  test_os_target:
    name: Test ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-container:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # axvisor
          - os: axvisor
            target: x86_64-unknown-none
          - os: axvisor
            target: riscv64gc-unknown-none-elf
          - os: axvisor
            target: aarch64-unknown-none-softfloat
          # starry
          - os: starry
            target: riscv64gc-unknown-none-elf
          - os: starry
            target: aarch64-unknown-none-softfloat
          - os: starry
            target: loongarch64-unknown-none-softfloat
          # arceos
          - os: arceos
            target: x86_64-unknown-none
          - os: arceos
            target: riscv64gc-unknown-none-elf
          - os: arceos
            target: aarch64-unknown-none-softfloat
          - os: arceos
            target: loongarch64-unknown-none-softfloat
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - run: rustc --version

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: test
          cache-targets: false

      - name: Install ostool
        run: cargo install ostool --version ^0.8

      - name: Run ${{ matrix.os }} tests
        run: cargo xtask test ${{ matrix.os }} --target ${{ matrix.target }}
