baud_rate = "${env:BOARD_COMM_UART_BAUD}"
board_power_off_cmd = "${env:BOARD_POWER_OFF}"
board_reset_cmd = "${env:BOARD_POWER_RESET}"
dtb_file = "${env:BOARD_DTB}"
fail_regex = [
  "panicked at",
]
serial = "${env:BOARD_COMM_UART_DEV}"
success_regex = [
    "All tests passed!",
    "Hello World!",
    "root@firefly:~#",
    "^Phytium Pi",
    "Last login: *",
    "orangepi5plus login: *",
]
timeout = 300

[net]
interface = "${env:BOARD_COMM_NET_IFACE}"
tftp_dir = "${env:TFTP_DIR}"